
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

logging:
  level:
    root: info

okta:
  oauth2:
    client-id: 0oa2y7chn3T1iGRG85d7
    client-secret: J1NoTZAcgF9dHLJX1VHtmcjCyUw9f3U3XoFIq_B_
    issuer: https://dev-28051690.okta.com/oauth2/default
